--- 
extensions: 
- json
- another-extension
name: factory
wp: 
  productid: 91c43a60-6b30-012f-cf61-64b9e8d01d54
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-3.2.2
android: 
  version: 2.1
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
symbian: 
  uid: "0xe9121a49"
vendor: rhomobile
sdkversion: 3.2.1
iphone: 
  BundleURLScheme: factory
  provisionprofile: 
  BundleIdentifier: com.rhomobile.factory
  sdk: iphonesimulator5.0
  entitlements: 
  codesignidentity: 
  configuration: Release
